# Ad. Sale Prediction from Existing customer -Logistic Regression

#### Importing libraries

In [1]:
import pandas as pd
import numpy as np

#### Load dataset

In [2]:
dataset=pd.read_csv('Ad_sale_dataset.csv')

#### Summarize dataset

In [3]:
print(dataset.shape)
print(dataset.head(5))

(49, 3)
   Age  Salary  Result
0   19   19000       0
1   35   20000       0
2   26   43000       0
3   27   57000       0
4   19   76000       1


#### Segregate dataset into X(input/independent variable)and Y(output/dependent variable)

In [4]:
X=dataset.iloc[:,:-1].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  52000],
       [    26,  66000],
       [    20,  18000],
       [    32,  82000],
       [    18,  80000],
       [    29,  25000],
       [    47,  26000],
       [    45,  28000],
       [    46,  28000],
       [    32, 100000],
       [    25,  90000],
       [    37,  33000],
       [    35,  38000],
       [    33,  69000],
       [    18,  86000],
       [    22,  55000],
       [    35, 710000],
       [    29, 148000],
       [    29,  47000],
       [    21,  88000],
       [    34, 115000],
       [    26, 118000],
       [    34,  43000],
       [    34,  72000],
       [    23,  28000],
       [    35,  47000],
       [    25,  22000],
       [    24,  23000],
       [    31,  34000],
       [    21,  50000],


In [5]:
Y=dataset.iloc[:,-1].values
Y

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0], dtype=int64)

#### Splitting dataset into train and test

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

#### Feature Scaling : test data should be completely new and a surprise set for our model

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


#### Training

In [8]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(random_state=0)
model.fit(X_train,y_train)

LogisticRegression(random_state=0)

#### Predicting whether new customer with age and salary will buy or not

In [12]:
age=int(input("Enter New Customer Age:"))
sal=int(input("Enter New Customer Salary:"))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result==1:
    print("Customer will Buy")
else:
    print("Customer will not Buy")

Enter New Customer Age:55
Enter New Customer Salary:345000
[1]
Customer will Buy


#### Prediction for all test data

In [13]:
y_pred=model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]]


#### Evaluating model -CONFUSION MATRIX

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)

print("Confusion Matrix:")
print(cm)

print("Accuracy of the Model: {0}%".format(accuracy_score(y_test,y_pred)*100))

Confusion Matrix:
[[7 0]
 [5 1]]
Accuracy of the Model: 61.53846153846154%
